import "./globals.css";
// import { Inter, IBM_Plex_Sans } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });
// const plex = IBM_Plex_Sans({
//   weight: ["400", "500", "600", "700"],
//   subsets: ["latin"],
// });
import localFont from "next/font/local";

const inter = localFont({
  src: "../public/fonts/Inter.var.woff2",
  display: "swap",
});

export const metadata = {
  title: "Open Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
